# Generated by Django 2.2.4 on 2019-08-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
