# Generated by Django 2.2.4 on 2019-08-06 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0002_auto_20190806_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='wzWgsy7setKcUYfmTXeXENAEEWXyTGhGYQiLe0lrcrQ9fLorFjC9AUSAb6CLnBOmR4ZTruCxgs5HY9pjVZnjUsyFPiyhsTOUCpweEWPDltRDjSWMbkfuYwTP', max_length=120)),
                ('expire', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
