# Generated by Django 2.2.4 on 2019-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0003_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preview_image', models.ImageField(upload_to='')),
                ('Images', models.ImageField(upload_to='')),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='ugsF3CwtRq8AgLbmDcJTyBekIMuKpUcvs2H9RCTQ1tDhUgzvqMwvYHumyjDfpyaN38n1X3FTFZYZ5Y0euuWnGri19PCbOsrqKESDCb551V7DgRiDZNgpzueA', max_length=120),
        ),
    ]
