# Generated by Django 2.2.4 on 2019-08-08 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0005_auto_20190807_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='lfpwwNRmzoLfFE8y2LBKPU5h1I4HgqRxTp7uvHhp7uycQ1KAxMJ1gKqlTZ5rTwd3ZWR6t8K8ZMprmiReMjWeSVTe3whixKRWZCxMafMpPj1C6iN6cBiSkDWn', max_length=120),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
