# Generated by Django 2.2.4 on 2019-08-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0006_auto_20190808_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='aR3401ILWkK9PjAegigxYNfUvdEhJKqmfQExH9WDuNYuYMvvUyAbW78es9BxsLtSs52OUDCX1R7Tn8YfzYhwXD3uf07LAV8PWg0M4p9A3a33hyQMEan1Wd3p', max_length=120),
        ),
    ]
