# Generated by Django 2.2.4 on 2019-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0007_auto_20190808_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settingprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settingprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='AfXLszo6Rppkd3UWOhlGLaZQCSFdQUtRi9Qnk3nnjg5KvkAlfG4dqCnsTjWYasAYUO96ql4HAeeBCAwazN1HVTYLzn110fYgC1k80s57JSvD0ZvHD5CrkZoQ', max_length=120),
        ),
    ]
