# Generated by Django 2.2.4 on 2019-08-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0008_auto_20190808_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='yNoLcBVYYEglnxwiZ8LsR54YQW1LWHBg8ZNOlSRf1dgU0l2yComKhtm1VCZrKuwVAkPUnRBRXlrxjQ4WbBp3ZL1ZFmmlW4m41k6RfEKPbkuncKlZDvLAJ4NY', max_length=120),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
