# Generated by Django 2.2.4 on 2019-08-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0009_auto_20190808_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingProfile',
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='yG5tGlcVq9JRlljXdP3KBI8CAc8lz165BZ4uxH62W1djTUQNCLyRDGVIoenvREVqO7f6linmAwxcXf1E1uDBxASVYvoSAhtadQYh0IgrdEwrotfvKPpjhJOF', max_length=120),
        ),
    ]
