# Generated by Django 2.2.4 on 2019-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0011_auto_20190810_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsettings',
            name='Facebook',
        ),
        migrations.RemoveField(
            model_name='socialsettings',
            name='Googleplus',
        ),
        migrations.RemoveField(
            model_name='socialsettings',
            name='Instagram',
        ),
        migrations.RemoveField(
            model_name='socialsettings',
            name='Linkedin',
        ),
        migrations.RemoveField(
            model_name='socialsettings',
            name='Twitter',
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='tGXNifDz4ahavjPEfAxiGmFHaXJ2n7U8qicpm5CU16OunaaybwjDeTnOuDpifvHsLPRJxLYPtduX0EKgVmS4GTeKRNCbczus6hfBRZCdzMi02BpkMsv2tecG', max_length=120),
        ),
    ]
