# Generated by Django 2.2.4 on 2019-08-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0012_auto_20190810_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsettings',
            name='Website',
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='dUdleLFLAcGS0pyHmTmGxh6iDWvdV4tQMqiS1uFggXZlozmgYuozBgxgCXCQaOPyPumntbAVQ2YaoW5h2RyHN5w3mmpJB2KHbmQCyRCqEGBCMgfe4EuUXEtm', max_length=120),
        ),
    ]
