# Generated by Django 2.2.4 on 2019-08-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0014_auto_20190810_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='0jfaUPvUVOAEPnI2lz3sbEt0KBlxfJnxwKXWho4MDYhJI1fUIV872DljB7W0PfKHOc2cgsKf6fq6OWeYMl2X4rPSGKThz2Vb6Kq1OEKrpN832joRC9lNx8PQ', max_length=120),
        ),
    ]
