# Generated by Django 2.2.4 on 2019-08-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0015_auto_20190811_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meta_data',
            old_name='tag',
            new_name='aspect',
        ),
        migrations.AddField(
            model_name='meta_data',
            name='lisence',
            field=models.CharField(blank=True, choices=[('Lisence', 'Lisence'), ('GPL', 'GPL'), ('MIT', 'MIT'), ('Apache', 'Apache'), ('BSD', 'BSD'), ('CCO', 'CCO'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meta_data',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meta_data',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='G51EAy3S8UdJtWh4UlkyNTFaZoqBoZwAKC3E6dbGunQbbjnqTd0xuw9tRUngXTsthjLmsbZBhWa0AIKdseDk4tdckI3VI9zCpJR0NBltn1d46K2nb47V4nif', max_length=120),
        ),
    ]
