# Generated by Django 2.2.4 on 2019-08-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0016_auto_20190811_0820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta_Data',
            new_name='MetaData',
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='Fru2zycgRwi6FGzeoRTIBCLBfGsEO038yJFisyzOeJCHtJ4nFpB0RGUZOp50aKrJvhLHTpGvVJ8CwDXAmztb4YXm6PGC2V8gFzhYl0XSIwzmBnXLeFYKLcQZ', max_length=120),
        ),
    ]
