# Generated by Django 2.2.4 on 2019-08-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0017_auto_20190811_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotdetails',
            name='Images',
        ),
        migrations.AlterField(
            model_name='shotdetails',
            name='Preview_image',
            field=models.ImageField(upload_to='shotadd/'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='DkPZyeDj78THoMupDTE0DBn5qsO58v6UuplnCxvDObkAWQIy7bKUrw6yNxVZlEunj0f9zUpA0rlycc3W2smKQeCKp2GKfxwPVknit56SF3SMzunTqceH43go', max_length=120),
        ),
        migrations.CreateModel(
            name='AddImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='shotadd/')),
                ('image_token', models.CharField(blank=True, max_length=255, null=True)),
                ('shotdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hm_blog.ShotDetails')),
            ],
        ),
    ]
