# Generated by Django 2.2.4 on 2019-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0018_auto_20190812_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotdetails',
            name='Preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='shotadd/'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='sdch7qCvM2Qf7T2kiV6zvGNm8FO9jv6ZoWjecdWqV84GeJaLCoBZHlPuTzIv9EHaipb7IF1AGrdLXu9IRconHVbzQnF3erxeHqPjB6m79UytbORXWzAd417Z', max_length=120),
        ),
    ]
