# Generated by Django 2.2.4 on 2019-08-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0019_auto_20190812_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaData',
        ),
        migrations.AddField(
            model_name='shotdetails',
            name='aspect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shotdetails',
            name='lisence',
            field=models.CharField(blank=True, choices=[('Lisence', 'Lisence'), ('GPL', 'GPL'), ('MIT', 'MIT'), ('Apache', 'Apache'), ('BSD', 'BSD'), ('CCO', 'CCO'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shotdetails',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shotdetails',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='Hzv6o6FiKwtJuinBrqxEg8KkBReMpcARTlinQXBC5PghbVkgnozo9KLDlSeRdTtdojFXjgO1tfC4OLOuyQitqM7UcsN7rLkfRB498quIJrr8cGfikPTo96Br', max_length=120),
        ),
    ]
