# Generated by Django 2.2.4 on 2019-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0020_auto_20190812_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='NTg9UgSgsZVMIxG2x6e4YoFQ4jjfFHIUEkAUPn0JTZX6ZZp4pKvAQU6ff3hrNVn4zEGeUMoXwOaUInunG67iwMhG7nt1dZZCqUiuvFbYe5czhtAiAUq0hidN', max_length=120),
        ),
    ]
