# Generated by Django 2.2.4 on 2019-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0021_auto_20190812_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='WXStmlfkfSwmPL1heiqe68WJA0bfc0uPOENMjMFEYPaxuJFM10chey18e8mvn4cujICl11DICDRkGDWNODUuFSCXQYKodVJJ8P1g7qGklauan9WAdZuufBse', max_length=120),
        ),
    ]
