# Generated by Django 2.2.4 on 2019-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0022_auto_20190812_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='kTNpT2c71SD4hTvQ6sfurV3vmDWzzeX3O9sZrKzMxQALPWPILgBTAcEI5GajWYIAUb56LLxYZcJcFAStDpBTk2kSt6a5QSlzFG9SSxxjDUwc8EaRlMD4or4A', max_length=120),
        ),
    ]
