# Generated by Django 2.2.4 on 2019-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0023_auto_20190812_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='WyyKHDjdTGTh408a11NBLJy6Nnps6DKGY7Y13xoz43IAl0ew4Kh4sFiK0kuFO2ThjEeuPAdwZI8zzEjI4rWFsUmSwNVz47YPg88gy7UpkyJgH8I9hDH5wL6C', max_length=120),
        ),
    ]
