# Generated by Django 2.2.4 on 2019-08-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0024_auto_20190812_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='OgSAJf4aYF0uTdjQUwf4TOrClQr0tqULnCqQ6FdW2suS6k2BE78rdKWJv2O56EfAKb2FWcnQQvqYcaQwTqmcLdyMTi0FEHgf6GK2P4EbcU0WF3LLSFYScOkx', max_length=120),
        ),
    ]
