# Generated by Django 2.2.4 on 2019-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0025_auto_20190812_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdetails',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='DR86cPsx903w1DbJoQtKBTssPQObfAJ2KtmOoqd8FOuPMkuYez7vSYZzrzsw8KPKkpqaVzMwIw7sRb4g7bOIQV0LaxrZ0677aiM4W3QirKayaEDULMxYngVZ', max_length=120),
        ),
    ]
