# Generated by Django 2.2.4 on 2019-08-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0026_auto_20190814_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='ymjAsI6UOXmMKitDYIiAzgE4NU3usYjga3oOhzlYRPjQEvVepHfAoyzpaU4X0w8MewKAbTUemZrDKJ77FFNuPv1LrSawKdKDfgoQiCpVSDau7tYXbjpMS7b5', max_length=120),
        ),
    ]
