# Generated by Django 2.2.4 on 2019-08-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0027_auto_20190814_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotdetails',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='eqLcveCCLWRn0nVIoQLhWtJ32c3uPA9XRAXRfXrbOQjlSTr3Bfe2V1AkIYt6ovz0Nq6Xw3ZOmSDYNv3UgYZsiMRVim4wQsY6gBNVn45RtPF12NsAH4km4yLa', max_length=120),
        ),
    ]
