# Generated by Django 2.2.4 on 2019-08-14 14:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0028_auto_20190814_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_about', models.CharField(blank=True, max_length=255, null=True)),
                ('site_story', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_about_team', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('person_story', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='KtI2NGKfJqwIKjJAiHRnYJpyKScyZv4m2JOpR93xPGtEtsG3WbcLF8bOl32I7Akw12vtOWfmfxlSAzrHydN35FIvJTN3f7tvco704KEE8ItsXYMZ0zdVlcuT', max_length=120),
        ),
    ]
