# Generated by Django 2.2.4 on 2019-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0030_auto_20190814_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addimages',
            name='Images',
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='56Hb1pnVdkctmoPay241BQRFjPUQeMX3kiMFNFdHmdjeg4LNhjv1fEINsn79oQiij50LohLFf52AYkj9RuZCNuXS4ElkctWAXAkfqO4udo5Xoc80tfMyppo1', max_length=120),
        ),
    ]
