# Generated by Django 2.2.4 on 2019-08-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0032_auto_20190815_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='my1oPVLpigOLL8KhWAtuZO1XlWtJLKAmhUUkoALXqTHgt4Gu8baT06O76mRBjzWf17y2aA8royafzDpceVGUYp2rBm3ExNcSTYDjKG48l0iUBa4xiVicvjX8', max_length=120),
        ),
    ]
