# Generated by Django 2.2.4 on 2019-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0033_auto_20190815_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='UA9PgvAWHfGB8dvCaXwWvavm1R7YXPqKvnSUM3KHxNk0P2Cj6czgaOPeB6lD2jS6FAJvcwF9Ap2ZbkCowwNp8faYqxLnPPmcRQkjf39pphVIFLXmLYF2mNCt', max_length=120),
        ),
    ]
