# Generated by Django 2.2.4 on 2019-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0034_auto_20190815_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='AGC1bsXtYQERDCV4DchRm08qtsUmmny5GDDEmVwBUmUrDplq6mHxhJA1IWf6yEWrRW1QDLHr4afkfqhQQ3nb5F2ZIzc6iXIECWiLdlywoAVZ1Ji9clhkmFbr', max_length=120),
        ),
    ]
