# Generated by Django 2.2.4 on 2019-08-15 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0035_auto_20190815_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdetails',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='fjUnqR8YQKapJUSm0U3g7i5iytZx5Gjuk1B6GrsfO07gre2BDu65VZfdjdDMU8Lsw4iHXvSPitsNoLMNNqvVVRUXL1FTqRy60GDsBLAU5WVo56STDov0dMbR', max_length=120),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Like'), (1, 'Unlike')], default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hm_blog.ShotDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
