# Generated by Django 2.2.4 on 2019-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0036_auto_20190815_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotdetails',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default='vArde6ALRnj4SPNUMNHid3Yk755d42ILjafUggd8ZPcl8tiQSH6XFL5tYR5W91n5Q1G4h22J526lYoNEdzTUOyIUuUWrbBwRU01AMWaHnCYbf7APBURRErN9', max_length=120),
        ),
    ]
