# Generated by Django 2.2.4 on 2019-08-15 17:00

from django.db import migrations, models
import hm_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0037_auto_20190815_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(default=hm_blog.models.generate_token, max_length=120),
        ),
    ]
