# Generated by Django 2.2.4 on 2019-08-19 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0038_auto_20190815_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdetails',
            name='Post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
