# Generated by Django 2.2.4 on 2019-08-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0039_shotdetails_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shotdetails',
            old_name='Post',
            new_name='user',
        ),
    ]
