# Generated by Django 2.2.4 on 2019-08-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0042_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
