# Generated by Django 2.2.4 on 2019-08-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0044_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='location',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='tel',
        ),
        migrations.AddField(
            model_name='contactus',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
