# Generated by Django 2.2.4 on 2019-08-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0045_auto_20190820_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
