# Generated by Django 2.2.4 on 2019-08-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0046_auto_20190820_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
