# Generated by Django 2.2.4 on 2019-08-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0048_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='shot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hm_blog.ShotDetails'),
        ),
    ]
