# Generated by Django 2.2.4 on 2019-08-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0049_comment_shot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='name',
        ),
    ]
