# Generated by Django 2.2.4 on 2019-08-21 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0051_contactformmodel_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdetails',
            name='view',
            field=models.ManyToManyField(related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
