# Generated by Django 2.2.4 on 2019-08-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0052_shotdetails_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdetails',
            name='comm_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
