# Generated by Django 2.2.4 on 2019-08-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0053_shotdetails_comm_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotdetails',
            name='comm_count',
        ),
    ]
