# Generated by Django 2.2.4 on 2019-08-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0054_remove_shotdetails_comm_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addimages',
            old_name='Images',
            new_name='image',
        ),
    ]
