# Generated by Django 2.2.4 on 2019-08-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0055_auto_20190823_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shotdetails',
            options={'ordering': ['-id']},
        ),
    ]
