# Generated by Django 2.2.4 on 2019-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0056_auto_20190829_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='verification_type',
            field=models.IntegerField(choices=[(0, 'Password'), (1, 'Email')], default=0),
        ),
    ]
