# Generated by Django 2.2.4 on 2019-09-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_blog', '0057_verification_verification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='following_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='my following list'),
        ),
    ]
